import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const links = [
    { url: "#intro", text: "intro" },
    { url: "#about", text: "about" },
    { url: "#projects", text: "projects" },
    { url: "#blogs", text: "blogs" },
    { url: "#skills", text: "skills" },
  ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar websiteTitle="Portfolio" links={links} />
        <section className="max-w-75r mx-auto">{children}</section>
      </body>
    </html>
  );
}
