# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
       APP_ENV: github-pages

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Yarn Install
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install       
    - name: Build
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build
    - name: Export
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: export
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages
        folder: out
